services:
  app:
    build: ./app
    container_name: node-app
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo
    networks:
      - app-network

    # Security Best Practices
    # read_only: true

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

    tmpfs:
      - /tmp

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki/local-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    networks:
      - app-network

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - ./observability/promtail/config.yaml:/etc/promtail/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
    networks:
      - app-network

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_DEFAULT_THEME: light
    volumes:
      - grafana-data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - loki
    networks:
      - app-network

  mongo:
    image: mongo:7
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${Mongodb_root_username}
      MONGO_INITDB_ROOT_PASSWORD: ${Mongodb_root_password}
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${Mongodb_root_username}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${Mongodb_root_password}
      ME_CONFIG_MONGODB_SERVER: mongo-db
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:
  loki-data:
  grafana-data:
networks:
  app-network:
    # name: app-network ->if you want to specify a custom name for the network
    driver: bridge
